name: Tag Reaction
on:
  push:
    tags:
      - '@dynamic-framework/*@*'

jobs:
  build:
    name: Reaction
    runs-on: ubuntu-latest
    outputs:
      build-artifact: ${{ steps.upload-artifact.outputs.artifact-path }}
    steps:
      - name: Greeting
        run: |
          echo "Hello..."
      
